language: python
python:
  - "3.11"
dist: jammy
install:
  - pip install uv
  - travis_retry uv pip install -U -r doc/requirements.txt
  - travis_retry uv pip install -e .[dev, vis]
after_success:
  - make -C doc html
  - touch /home/travis/build/ae-bii/nlgm/doc/build/html/.nojekyll
script:
  - pytest
branches:
  only:
    - main
deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
  local_dir: doc/build/html
  edge: true
