language: python
python:
  - "3.11"
install:
  - pip install -r requirements.txt
  - travis_retry pip install -U -r doc/requirements.txt
after_success:
  - make -C doc html
script:
  - pytest
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
  local_dir: doc/build/html
dist: jammy