name: Ruff
on:
  push:
    paths:
      - src/**
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: './src'
          args: 'format --check'
